### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by Leedorado** [uxh/shadowsocks_bash#3]
vultr的日本节点安装报错，信息如下：
mbedtls-2.11.0-gpl.tgz 下载失败，请稍后重试！
请问如何解决，谢谢^^

**Comment by uxh** [comment]
源文件地址：
https://tls.mbed.org/download/mbedtls-2.11.0-gpl.tgz
可以用 wget 手动下载：
wget https://tls.mbed.org/download/mbedtls-2.11.0-gpl.tgz
